### ISSUE TITLE
Inclusion of tags

### ISSUE THREAD

**Issue by wittenator** [nicholasmfraser/covid19_preprints#11]
Thanks a lot for the data harvesting! I am currently trying to build a data visualization on top of the dataset and I noticed that having the tags with which a paper was tagged would help me a lot. As far as I know, Crossref, Arxiv, etc. provide tags out-of-the-box. Would it be possible to add these to the dataset?

**Comment by nicholasmfraser** [comment]
Hi @wittenator! Can you be more specific which tags you are exactly referring to (or give an example)? Here is an example API call for a bioRxiv preprint on Crossref: http://api.crossref.org/works/10.1101/2021.02.09.430517. Can you point me to the "tags" property you are interested in?

**Comment by wittenator** [comment]
Ah damn, Crossref does not seem to include such data. I was actually looking for something like the Arxiv Subclasses (https://arxiv.org/corr/subjectclasses). Do you know by any chance if the other datasources besides Crossref have something similar?

**Comment by nicholasmfraser** [comment]
Oh I see now. Some sources may include subject classifications (in fact, bioRxiv does have a kind of subject classification, under the "group-title" field in the link I shared above), but as far as I know these are provided directly by each individual source and are not standardised in terms of the categories used, nor in how they are represented in the relevant metadata. You would need to investigate each individual source directly - for now (for reasons of time and simplicity) I don't plan to add those data to this repository.

**Comment by bmkramer** [comment]
To add to this, Crossref has subject classification included only for a subset of records, in the ["category-name" field](https://github.com/CrossRef/rest-api-doc#filter-names) (based on Scopus' ASJC classification). 

An additional approach (and partial solution to the issue of source-specific subject classifications) could be to explore using subject classification used in a broad bibliographic database like Lens, Dimensions or Microsoft Academic. All of these cover a relatively broad range of preprints, but not our full dataset unfortunately.

I agree with @nicholasmfraser about not including subject data in this repository for reasons of time and simplicity.

**Comment by wittenator** [comment]
Thanks a lot for your replies and the pointers! It definitely makes sense to not include this data since it would be a rather sparsely populated column. I'll definitely have a look at the subject classification from Lens etc. . Otherwise, I'll probably just run some topic modeling algorithm and extract keywords from there. That should hopefully do the trick.
