### ISSUE TITLE
Figshare versions?

### ISSUE THREAD

**Issue by J535D165** [nicholasmfraser/covid19_preprints#21]
Are there still versions uploaded to figshare? The last version is outdated. 

There is an option to auto-upload the data with GitHub actions https://help.figshare.com/article/how-to-connect-figshare-with-your-github-account

**Comment by nicholasmfraser** [comment]
Hi @J535D165, apologies and thanks for the reminder. I just started uploading the "missing" versions sequentially to figshare (i.e. each biweekly release) but have apparently now reached the maximum number of versions allowable on figshare (50). I've written to their support team to increase the limit and will then upload the remaining releases.

I initially tried syncing the repository to figshare via github actions but encountered technical problems (e.g. releases not being synced, or duplicated) that then took time to solve. But, as that was more than a year ago, I'll look into it again.

**Comment by nicholasmfraser** [comment]
The remaining versions have now also been uploaded to figshare (up to the latest release, 2021-07-25)
